version: '3'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment: 
      SERIVE_NAME: app
      SERVICE_TAG: dev
    working_dir: /var/www
    networks: 
      - app-network
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
      - "443:443"
    networks: 
      - app-network
networks: 
  app-network:
    driver: bridge